#!/usr/bin/ruby

guard 'rspec', :notification => false do
  watch(%r{^/spec/specs/.+_spec\.rb$})
  watch(%r{^scripts/backup_current/(.+)\.rb$})     { |m| "spec/specs/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end


